issue_tracker_root/issue_tracker/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('issues.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

issue_tracker_root/issues/urls.py
from django.urls import path

from .views import (
    DashboardView,
    ProjectsListView,
    AddProjectView,
    EditProjectView,
    DeleteProjectView,
    ProjectDetailView,
    IssueDetailView,
    AddIssueView,
    EditIssueView,
    DeleteAttachmentView,
    AddCommentView,
    EditCommentView,
    DeleteCommentView,
    AssignedToMeView,
)

app_name = "issues"

urlpatterns = [
    path("", DashboardView.as_view(), name="dashboard"),
    path("my-issues/", AssignedToMeView.as_view(), name="my-issues"),

    path("projects/", ProjectsListView.as_view(), name="projects-list"),
    path("projects/add/", AddProjectView.as_view(), name="add-project"),
    path("projects/<slug:slug>/update/", EditProjectView.as_view(), name="update-project"),
    path(
        "projects/<slug:slug>/delete/", DeleteProjectView.as_view(), name="delete-project"
    ),
    path("projects/<slug:slug>/", ProjectDetailView.as_view(), name="project-detail"),

    path("projects/<slug:slug>/add/", AddIssueView.as_view(), name="add-issue"),
    path(
        "projects/<str:project_slug>/<slug:slug>/",
        IssueDetailView.as_view(),
        name="issue-detail",
    ),
    path(
        "projects/<str:project_slug>/<slug:slug>/edit/",
        EditIssueView.as_view(),
        name="edit-issue",
    ),

    path(
        "projects/<str:project_slug>/<str:issue_slug>/<int:pk>/delete-attachment/",
        DeleteAttachmentView.as_view(),
        name="delete-attachment",
    ),

    path(
        "projects/<str:project_slug>/<slug:slug>/add-comment/",
        AddCommentView.as_view(),
        name="add-comment",
    ),
    path(
        "projects/<str:project_slug>/<str:issue_slug>/<int:pk>/edit-comment/",
        EditCommentView.as_view(),
        name="edit-comment",
    ),
    path(
        "projects/<str:project_slug>/<str:issue_slug>/<int:pk>/delete-comment/",
        DeleteCommentView.as_view(),
        name="delete-comment",
    ),
]

issue_tracker_root/templates/partials/_alerts.html
{% load static%}

{% if messages %}
{% for message in messages %}
<div id="message" class="container">
  <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Zamknij"><span aria-hiden="true">&times;</span>
    </button>
    <strong>
      {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
      Uwaga:
      {% endif %}
    </strong>
    {{ message }}
  </div>
</div>
{% endfor %}
{% endif %}


{% if form.non_field_errors %}
<div id="error" class="container">
  <div class="alert alert-danger" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Zamknij"><span aria-hiden="true">&times;</span>
    </button>
    <strong>UWAGA!</strong>
    {% for error in form.non_field_errors %}
    {{ error }}
    {% endfor %}
  </div>
</div>
{% endif %}

issue_tracker_root/templates/partials/_navbar.html
{% load static %}

<!-- Navbar -->
  <nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#"><i class="fas fa-bars"></i></a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="{% url 'issues:dashboard' %}" class="nav-link">Home</a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="https://github.com/efefre/issue_tracker" target="_blank" title="Github Repository" class="nav-link"><i class="fab fa-github"></i> GitHub</a>
      </li>
    </ul>

    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
      <li nav-item>
        <a href="{% url 'account_logout' %}" class="nav-link">Sign out</a>
      </li>
    </ul>
  </nav>
  <!-- /.navbar -->

issue_tracker_root/templates/partials/_sidebar.html
{% load issues_extras %}
{% load static %}


<!-- Main Sidebar Container -->
  <aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a href="{% url 'issues:dashboard' %}" class="brand-link">
      <span class="brand-text font-weight-light">Issue Tracker</span>
    </a>


    <!-- Sidebar -->
    <div class="sidebar">
      <!-- Sidebar user panel (optional) -->
      <div class="user-panel mt-3 pb-3 mb-3 d-flex">
        {% if request.user.profile_img %}
        <div class="image">
          <img src="/media/{{request.user.profile_img}}" class="img-circle elevation-2" alt="User Image">
        </div>
        <div class="info">
          <a href="#" class="d-block">{{request.user}}</a>
        </div>
        {% else %}
        <div class="info">
          Welcome, <a href="#" class="d-block">{{request.user}}</a>
        </div>
        {% endif %}
      </div>

      <!-- Sidebar Menu -->
      <nav class="mt-2">
        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
           <li class="nav-item">
            <a href="{% url 'issues:dashboard' %}"
               {% if request.path == '/' %}
                  class="nav-link active">
                {% else %}
                  class="nav-link">
                {% endif %}
              <i class="nav-icon fas fa-tachometer-alt"></i><p>Home</p>
            </a>
          </li>
          <li class="nav-item">
            <a href="{% url 'issues:my-issues' %}"
               {% if request.path == '/my-issues/' %}
                  class="nav-link active">
                {% else %}
                  class="nav-link">
                {% endif %}
              <i class="nav-icon fas fa-user-check"></i><p>Assigned to Me</p>
            </a>
          </li>
          <li class="nav-item has-treeview menu-open">
            <a href="{% url 'issues:projects-list' %}" class="nav-link">
              <i class="nav-icon fas fa-tasks"></i>
              <p>
                Projects
                <i class="right fas fa-angle-left"></i>
              </p>
            </a>
            <ul class="nav nav-treeview">
              <li class="nav-item">
                  <a href="{% url 'issues:projects-list' %}"
                     {% if request.path == '/projects/' %}
                      class="nav-link active">
                    {% else %}
                      class="nav-link">
                    {% endif %}
                    <i class="nav-icon fas fa-list"></i>
                    <p>All projects</p>
                  </a>
                </li>

              {% projects_list as projects %}

              {% for project in projects %}
                <li class="nav-item">
                  <a href="{% url 'issues:project-detail' slug=project.slug %}"
                     {% if request.path == '/project/'|add:project.slug %}
                      class="nav-link active">
                    {% else %}
                      class="nav-link">
                    {% endif %}
                    <i class="nav-icon fas fa-clipboard-list"></i>
                    <p>{{project.name}}</p>
                  </a>
                </li>
              {% endfor %}
            </ul>
          </li>
        </ul>
      </nav>
      <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
  </aside>