issue_tracker_root/issue_tracker/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('issues.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

issue_tracker_root/issues/urls.py
from django.urls import path

from .views import (
    DashboardView,
    ProjectsListView,
    AddProjectView,
    EditProjectView,
    DeleteProjectView,
    ProjectDetailView,
    IssueDetailView,
    AddIssueView,
    EditIssueView,
    DeleteAttachmentView,
    AddCommentView,
    EditCommentView,
    DeleteCommentView,
    AssignedToMeView,
)

app_name = "issues"

urlpatterns = [
    path("", DashboardView.as_view(), name="dashboard"),
    path("my-issues/", AssignedToMeView.as_view(), name="my-issues"),

    path("projects/", ProjectsListView.as_view(), name="projects-list"),
    path("projects/add/", AddProjectView.as_view(), name="add-project"),
    path("projects/<slug:slug>/update/", EditProjectView.as_view(), name="update-project"),
    path(
        "projects/<slug:slug>/delete/", DeleteProjectView.as_view(), name="delete-project"
    ),
    path("projects/<slug:slug>/", ProjectDetailView.as_view(), name="project-detail"),

    path("projects/<slug:slug>/add/", AddIssueView.as_view(), name="add-issue"),
    path(
        "projects/<str:project_slug>/<slug:slug>/",
        IssueDetailView.as_view(),
        name="issue-detail",
    ),
    path(
        "projects/<str:project_slug>/<slug:slug>/edit/",
        EditIssueView.as_view(),
        name="edit-issue",
    ),

    path(
        "projects/<str:project_slug>/<str:issue_slug>/<int:pk>/delete-attachment/",
        DeleteAttachmentView.as_view(),
        name="delete-attachment",
    ),

    path(
        "projects/<str:project_slug>/<slug:slug>/add-comment/",
        AddCommentView.as_view(),
        name="add-comment",
    ),
    path(
        "projects/<str:project_slug>/<str:issue_slug>/<int:pk>/edit-comment/",
        EditCommentView.as_view(),
        name="edit-comment",
    ),
    path(
        "projects/<str:project_slug>/<str:issue_slug>/<int:pk>/delete-comment/",
        DeleteCommentView.as_view(),
        name="delete-comment",
    ),
]

issue_tracker_root/issues/models.py
from django.conf import settings
from django.db import models
from django.urls import reverse
from django.utils.translation import gettext as _
from django.core.validators import RegexValidator
import pendulum


# Create your models here.
class Project(models.Model):
    PROJECT_STATUS_CHOICES = [
        ("in progress", "In progress"),
        ("success", "Success"),
        ("cancel", "Cancel"),
    ]

    only_letters = RegexValidator(r"^[A-Z]*$", "Only capital letters are allowed.")

    name = models.TextField(verbose_name=_("Project name"), unique=True)
    slug = models.SlugField(max_length=10, validators=[only_letters], unique=True)
    status = models.CharField(
        choices=PROJECT_STATUS_CHOICES,
        default="in progress",
        verbose_name=_("Project status"),
        max_length=20,
    )
    created = models.DateTimeField(auto_now_add=True, verbose_name=_("Created"))

    def __str__(self):
        return self.name

    def done_issues_in_project(self):
        count = 0
        for issue in self.issues.all():
            if issue.status == "done":
                count += 1
        return count


class Issue(models.Model):

    ISSUE_TYPE_CHOICES = [("task", "Task"), ("bug", "Bug")]

    ISSUE_STATUS_CHOICES = [
        ("to do", "To do"),
        ("in progress", "In progress"),
        ("done", "Done"),
        ("cancel", "Cancel"),
    ]

    PRIORITY_CHOICES = [("high", "High"), ("medium", "Medium"), ("low", "Low")]

    ENVIRONMENT_CHOICES = [
        ("local", "Local"),
        ("dev", "Development"),
        ("test", "Test"),
        ("stage", "Stage"),
        ("prod", "Production"),
    ]

    project = models.ForeignKey(
        Project,
        on_delete=models.CASCADE,
        related_name="issues",
        verbose_name=_("Project"),
    )
    type = models.CharField(
        choices=ISSUE_TYPE_CHOICES,
        default="task",
        verbose_name=_("Issue type"),
        max_length=5,
    )
    status = models.CharField(
        choices=ISSUE_STATUS_CHOICES,
        default="to do",
        verbose_name=_("Issue status"),
        max_length=20,
    )
    priority = models.CharField(
        choices=PRIORITY_CHOICES,
        default="low",
        verbose_name=_("Issue priority"),
        max_length=10,
    )
    assignee = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="issues_assignee",
        verbose_name=_("Assignee"),
    )
    reporter = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="issues_reporter",
        verbose_name=_("Reporter"),
    )
    created = models.DateTimeField(auto_now_add=True, verbose_name=_("Created"))
    updated = models.DateTimeField(auto_now=True, verbose_name=_("Updated"))
    summary = models.CharField(verbose_name=_("Summary"), max_length=80)
    description = models.TextField(verbose_name=_("Description"))
    environment = models.CharField(
        choices=ENVIRONMENT_CHOICES,
        verbose_name=_("Environment"),
        max_length=100,
        blank=True,
    )
    slug = models.SlugField(
        max_length=255,
        unique=True,
        blank=True,
        null=True,
        editable=False,
        db_index=True,
    )

    def create_slug(self):
        count_issue_in_project = Issue.objects.filter(project=self.project).count()
        if self.slug:
            issue_slug = self.slug
        else:
            issue_slug = count_issue_in_project + 1
        return issue_slug

    def save(self, *args, **kwargs):
        self.slug = self.create_slug()
        return super().save()

    def __str__(self):
        return f"{self.summary} (project: {self.project})"

    def get_absolute_url(self):
        return reverse(
            "issues:issue-detail",
            kwargs={"project_slug": self.project.slug, "slug": self.slug},
        )


class Comment(models.Model):
    text = models.TextField(verbose_name=_("Comment"))
    created = models.DateTimeField(auto_now_add=True, verbose_name=_("Created"))
    updated = models.DateTimeField(auto_now=True, verbose_name=_("Updated"))
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="comments",
        verbose_name=_("Author"),
    )
    issue = models.ForeignKey(
        Issue,
        on_delete=models.CASCADE,
        related_name="comments",
        verbose_name=_("Issue"),
    )

    def __str__(self):
        return f"Comment for issue {self.issue.summary}"


def get_attachment_path(instance, filename):
    datetime = pendulum.now("Europe/Warsaw")
    datetime = datetime.to_datetime_string().replace(":", "_")
    return "uploads/{0}/{1}-{2}".format(instance.issue.id, datetime, filename)


class Attachment(models.Model):
    issue = models.ForeignKey(
        Issue,
        on_delete=models.CASCADE,
        related_name="attachments",
        verbose_name=_("Issue"),
    )
    file = models.FileField(upload_to=get_attachment_path, verbose_name=_("File"))
    added = models.DateTimeField(auto_now_add=True, verbose_name=_("Added"))

    def get_type(self):
        if ".pdf" in str(self.file):
            return "pdf"
        elif ".xls" in str(self.file) or ".xlsx" in str(self.file):
            return "excel"
        elif ".doc" in str(self.file) or ".docx" in str(self.file):
            return "doc"
        else:
            return "image"

    def __str__(self):
        return f"Attachment from issue {self.issue.summary} (id: {self.issue.id})"

issue_tracker_root/issues/views.py
from django.contrib.auth.decorators import login_required

# Create your views here.
from django.db.models import Prefetch
from django.urls import reverse
from django.utils.decorators import method_decorator
from django.views.generic import (
    TemplateView,
    ListView,
    FormView,
    UpdateView,
    DeleteView,
    CreateView,
    DetailView,
)
from .forms import (
    AddProjectForm,
    EditProjectForm,
    AddIssueForm,
    EditIssueForm,
    AttachmentFormset,
    AddCommentForm,
    EditCommentForm,
)
from .models import Issue, Project, Attachment, Comment


@method_decorator(login_required, name="dispatch")
class DashboardView(TemplateView):
    model = Issue
    template_name = "issues/dashboard.html"


@method_decorator(login_required, name="dispatch")
class ProjectsListView(ListView):
    model = Project
    template_name = "issues/projects_list.html"

    def get_queryset(self):
        query = super().get_queryset().prefetch_related('issues').order_by("-created")
        return query


@method_decorator(login_required, name="dispatch")
class AddProjectView(FormView):
    template_name = "issues/add_project.html"
    form_class = AddProjectForm
    success_url = "/projects"

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)


@method_decorator(login_required, name="dispatch")
class EditProjectView(UpdateView):
    model = Project
    template_name = "issues/edit_project.html"
    form_class = EditProjectForm

    def get_success_url(self):
        return reverse("issues:projects-list")


@method_decorator(login_required, name="dispatch")
class DeleteProjectView(DeleteView):
    model = Project
    template_name = "issues/confirm_delete_project.html"
    context_object_name = "delete_project"
    success_url = "/projects"


@method_decorator(login_required, name="dispatch")
class ProjectDetailView(ListView):
    model = Project
    template_name = "issues/project_detail.html"

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        prefetch = Prefetch('issues', queryset=Issue.objects.select_related('assignee').all())
        context["project_detail"] = Project.objects.prefetch_related(prefetch).get(slug=self.kwargs["slug"])
        return context


@method_decorator(login_required, name="dispatch")
class IssueDetailView(DetailView):
    model = Issue
    template_name = "issues/issue.html"
    queryset = Issue.objects.select_related('assignee','reporter').all()
    context_object_name = "issue_detail"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        issue = self.get_object()

        context["comments"] = issue.comments.select_related("author").all()
        return context


@method_decorator(login_required, name="dispatch")
class AddIssueView(CreateView):
    template_name = "issues/add_issue.html"
    form_class = AddIssueForm
    model = Issue

    def get_success_url(self, **kwargs):
        return reverse(
            "issues:project-detail", kwargs={"slug": self.kwargs.get("slug")}
        )

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["project"] = Project.objects.get(slug=self.kwargs.get("slug"))
        context["attachment"] = AttachmentFormset()
        return context

    def form_valid(self, form):
        context = self.get_context_data()
        form = form.save(commit=False)
        form.reporter = self.request.user
        form.project = context["project"]
        form.save()

        formset = AttachmentFormset(
            self.request.POST, self.request.FILES, instance=form, prefix="attachments"
        )

        if formset.is_valid():
            formset.save()

        return super().form_valid(form)


@method_decorator(login_required, name="dispatch")
class EditIssueView(UpdateView):
    model = Issue
    template_name = "issues/edit_issue.html"
    form_class = EditIssueForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["attachment"] = AttachmentFormset()
        return context

    def form_valid(self, form):
        formset = AttachmentFormset(
            self.request.POST, self.request.FILES, prefix="attachments"
        )

        if formset.is_valid():
            self.object = form.save()
            formset.instance = self.object
            formset.save()

        return super().form_valid(form)


@method_decorator(login_required, name="dispatch")
class DeleteAttachmentView(DeleteView):
    model = Attachment
    template_name = "issues/confirm_delete_attachment.html"
    context_object_name = "delete_attachment"

    def get_success_url(self):
        issue = Issue.objects.get(attachments__pk=self.kwargs.get("pk"))
        issue_slug = issue.slug
        return reverse(
            "issues:edit-issue",
            kwargs={"project_slug": issue.project.slug, "slug": issue_slug},
        )


@method_decorator(login_required, name="dispatch")
class AddCommentView(CreateView):
    template_name = "issues/add_comment.html"
    form_class = AddCommentForm
    model = Comment

    def get_success_url(self):
        issue = Issue.objects.get(slug=self.kwargs.get("slug"))
        return reverse(
            "issues:issue-detail",
            kwargs={"project_slug": issue.project.slug, "slug": issue.slug},
        )

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["issue"] = Issue.objects.get(slug=self.kwargs.get("slug"))
        context["author"] = self.request.user
        return context

    def form_valid(self, form):
        context = self.get_context_data()
        form = form.save(commit=False)
        form.author = self.request.user
        form.issue = context["issue"]
        form.save()
        return super().form_valid(form)


@method_decorator(login_required, name="dispatch")
class EditCommentView(UpdateView):
    model = Comment
    template_name = "issues/edit_comment.html"
    form_class = EditCommentForm

    def get_success_url(self):
        issue = Issue.objects.get(comments__pk=self.kwargs.get("pk"))
        return reverse(
            "issues:issue-detail",
            kwargs={"project_slug": issue.project.slug, "slug": issue.slug},
        )

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context


@method_decorator(login_required, name="dispatch")
class DeleteCommentView(DeleteView):
    model = Comment
    template_name = "issues/confirm_delete_comment.html"
    context_object_name = "delete_comment"

    def get_success_url(self):
        issue = Issue.objects.get(comments__pk=self.kwargs.get("pk"))
        return reverse(
            "issues:issue-detail",
            kwargs={"project_slug": issue.project.slug, "slug": issue.slug},
        )


@method_decorator(login_required, name="dispatch")
class AssignedToMeView(ListView):
    model = Issue
    template_name = "issues/my_issue.html"
    context_object_name = "my_issue"

    def get_queryset(self):
        query = Issue.objects.select_related('project','reporter').filter(assignee=self.request.user)
        return query

issue_tracker_root/templates/issues/add_issue.html
{% extends "issues/base.html" %}
{% load i18n %}

{% block head_title %}{% trans "Add issue" %}{% endblock %}
{% block body_class %}sidebar-mini{% endblock body_class %}
{% block content %}

<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Add issue</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="{% url 'issues:dashboard' %}">Home</a></li>
                        <li class="breadcrumb-item"><a href="{% url 'issues:projects-list' %}">Projects</a></li>
                        <li class="breadcrumb-item"><a href="{% url 'issues:project-detail' slug=project.slug %}">{{project.name}}</a>
                        </li>
                        <li class="breadcrumb-item active">Add issue</li>
                    </ol>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>


    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <!-- left column -->
                <div class="col-md-12">
                    <!-- general form elements -->
                    <div class="card card-primary">
                        <div class="card-header">
                            <h3 class="card-title">Issue detail</h3>
                        </div>
                        <!-- /.card-header -->
                        <!-- form start -->
                        <form method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            <!-- card-body -->
                            <div class="card-body">
                                <div class="row">
                                    <div class="col-md-7">
                                        <div class="form-group">
                                            <label for="id_surname">Summary</label>
                                            {{ form.summary }}
                                        </div>
                                        <div class="form-group">
                                            <label for="id_type">Type</label>
                                            {{ form.type }}
                                        </div>
                                        <div class="form-group">
                                            <label for="id_status">Status</label>
                                            {{form.status}}
                                        </div>
                                        <div class="form-group">
                                            <label for="id_priority">Priority</label>
                                            {{form.priority}}
                                        </div>
                                        <div class="form-group">
                                            <label for="id_description">Description</label>
                                            {{form.description}}
                                        </div>
                                    </div>

                                    <div class="col-md-4 offset-md-1">
                                        <div class="form-group">
                                            <label for="id_assignee">Assignee</label>
                                            {{form.assignee}}
                                        </div>

                                        <div class="form-group">
                                            <label for="id_environment">Environment</label>
                                            {{form.environment}}
                                        </div>
                                        {{ attachment.management_form }}
                                        <p><b>Attachments</b></p>
                                        {% for form in attachment.forms %}
                                            <div class="form-group">
                                                {{form.file}}
                                            </div>
                                        {% endfor %}
                                    </div>
                                </div>


                            </div>
                            <!-- /.card-body -->

                            <div class="card-footer">
                                <a href="{% url 'issues:project-detail' slug=project.slug %}" class="pull-right btn btn-link">Cancel</a>
                                <button type="submit" class="btn btn-primary">Submit</button>
                            </div>
                        </form>
                    </div>
                    <!-- /.card -->
                    <!-- /.card-body -->
                </div>
                <!-- /.card -->
            </div>
            <!--/.col (right) -->
        </div>
        <!-- /.row -->
</div><!-- /.container-fluid -->
</section>
<!-- /.content -->
</div>
<!-- /.content-wrapper -->

{% endblock content %}

issue_tracker_root/templates/issues/edit_issue.html
{% extends "issues/base.html" %}
{% load i18n %}

{% block head_title %}{% trans 'Edit: '|add:issue.summary %}{% endblock %}
{% block body_class %}sidebar-mini{% endblock body_class %}
{% block content %}

<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <label for="id_surname">Summary</label>
                        <h1>{{form.summary}}</h1>
                    </div>
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="{% url 'issues:dashboard' %}">Home</a></li>
                            <li class="breadcrumb-item"><a href="{% url 'issues:projects-list' %}">Projects</a></li>
                            <li class="breadcrumb-item"><a href="{% url 'issues:project-detail' slug=issue.project.slug %}">{{issue.project.name}}</a></li>
                            <li class="breadcrumb-item active">Edit: {{issue.summary}}</li>
                        </ol>
                    </div>
                </div>
            </div><!-- /.container-fluid -->
        </section>

        <!-- Main content -->
        <section class="content">
            <!-- Default box -->
            <div class="card">
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-7">
                            <p>
                                <label for="id_type">Type:</label>
                                {{form.type}}
                            </p>
                            <p>
                                <label for="id_status">Status:</label>
                                {{form.status}}
                            </p>
                            <p>
                                <label for="id_priority">Priority:</label>
                                {{form.priority}}
                            </p>
                            <p>
                                <label for="id_environment">Environment:</label>
                                {{form.environment}}</p>
                            <p>
                                <label for="id_description">Description:</label>
                                {{form.description}}
                            </p>
                        </div>
                        <div class="col-md-4 offset-md-1">
                            <p>
                                <label for="id_assignee">Assignee:</label>
                                {{form.assignee}}
                            </p>
                            {{ attachment.management_form }}
                            <p><b>Attachments</b></p>
                            {% for form in attachment.forms %}
                                <div class="form-group">
                                    {{form.file}}
                                    {{form.file.error}}
                                </div>
                            {% endfor %}
                        </div>
                    </div>
                    <div class="row">
                        {% if issue.attachments.all %}
                        <h2 style="font-size: 1.6rem"><b>Attachments</b></h2>
                           <div class="row">
                               {% for attachment in issue.attachments.all %}
                                   <div class="col-2 text-center mb-4">
                                       {% if 'pdf' in attachment.get_type %}
                                            <span class="btn btn-outline-dark active"><i class="far fa-file-pdf"></i> File: pdf</span>
                                       {% elif 'doc' in attachment.get_type %}
                                          <span class="btn btn-outline-dark active"><i class="far fa-file-word"></i> File: doc</span>
                                        {% elif 'excel' in attachment.get_type %}
                                          <span class="btn btn-outline-dark active"><i class="far fa-file-excel"></i> File: excel</span>
                                       {% else %}
                                            <img src="/media/{{attachment.file}}" class="img-fluid img-thumbnail" />
                                       {% endif %}
                                        <small style="margin-top: 10px;">
                                            <br>Added:<br><b>{{attachment.added}}</b><br/>
                                        </small>
                                            <a href="{% url 'issues:delete-attachment' project_slug=attachment.issue.project.slug issue_slug=attachment.issue.slug pk=attachment.pk %}" class="btn btn-outline-danger btn-sm">
                                                <i class="fas fa-trash"></i></a>
                                   </div>
                               {% endfor %}
                           </div>
                        {% endif %}
                    </div>
                </div>
                <div class="card-footer">
                    <a href="{% url 'issues:issue-detail' project_slug=issue.project.slug slug=issue.slug %}" class="pull-right btn btn-link">Cancel</a>
                    <button type="submit" class="btn btn-primary">Submit</button>
                </div>
                <!-- /.card-body -->
            </div>
            <!-- /.card -->
        </section>
        <!-- /.content -->
    </form>
</div>
<!-- /.content-wrapper -->

{% endblock content %}

issue_tracker_root/templates/issues/projects_list.html
{% extends "issues/base.html" %}
{% load i18n %}

{% block head_title %}{% trans "Projects" %}{% endblock %}
{% block body_class %}sidebar-mini{% endblock body_class %}
{% block content %}

<!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1>Projects <a class="btn btn-primary btn-sm" href="{% url 'issues:add-project' %}"><i class="fas fa-plus"></i> Add</a></h1>
          </div>
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="{% url 'issues:dashboard' %}">Home</a></li>
              <li class="breadcrumb-item active">Projects</li>
            </ol>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
    {% if not project_list %}
        <p>There is no projects!</p>
    {% else %}
      <!-- Default box -->
      <div class="card">
        <div class="card-header">
          <h3 class="card-title">Projects</h3>
        </div>
        <div class="card-body p-0">
          <table class="table table-striped projects">
              <thead>
                  <tr>
                      <th style="width: 1%">
                          #
                      </th>
                      <th style="width: 20%">
                          Project Name
                      </th>
                      <th>
                          Project Progress
                      </th>
                      <th style="width: 8%" class="text-center">
                          Status
                      </th>
                      <th style="width: 30%">
                      </th>
                  </tr>
              </thead>
              <tbody>
              {% for project in project_list %}
                  <tr>
                      <td>
                          {{ forloop.counter }}
                      </td>
                      <td>
                          <a>
                              {{project.name}}
                          </a>
                          <br/>
                          <small>
                              Created: {{project.created}}
                          </small>
                      </td>
                      <td class="project_progress">
                          <small>All issues: {{project.issues.all|length}} | Done: {{project.done_issues_in_project}}</small>
                          <div class="progress progress-sm">
                              {% widthratio project.done_issues_in_project project.issues.all|length 100 as ratio %}
                              <div class="progress-bar bg-green" role="progressbar" aria-volumenow="{{project.done_issues_in_project}}" aria-volumemin="0" aria-volumemax="{{project.issues.all|length}}" style="width:{{ratio}}%">
                              </div>
                          </div>
                          <small>
                              {{ratio}}% Complete
                          </small>
                      </td>
                      <td class="project-state">
                          <span class="badge
                          {% if project.status == 'success' %}
                            badge-success
                          {% elif project.status == 'in progress' %}
                            badge-primary
                          {% elif project.status == 'cancel' %}
                            badge-danger
                          {% endif %}
                        ">{{project.status|upper}}</span>
                      </td>
                      <td class="project-actions text-right">
                          <a class="btn btn-primary btn-sm" href="{% url 'issues:project-detail' slug=project.slug %}">
                              <i class="fas fa-folder">
                              </i>
                              View
                          </a>
                          <a class="btn btn-info btn-sm" href="{% url 'issues:update-project' slug=project.slug %}">
                              <i class="fas fa-pencil-alt">
                              </i>
                              Edit
                          </a>
                          <a class="btn btn-danger btn-sm" href="{% url 'issues:delete-project' slug=project.slug %}">
                              <i class="fas fa-trash">
                              </i>
                              Delete
                          </a>
                      </td>
                  </tr>
              {% endfor %}
              </tbody>
          </table>
        </div>
        <!-- /.card-body -->
      </div>
      <!-- /.card -->
    {% endif %}
    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->

{% endblock content %}